# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Data Prepper AWS secrets End-to-end test with Gradle
on:
  push:
    branches: [ main ]
  pull_request_target:
    types: [ opened, synchronize, reopened ]
  workflow_dispatch:
# permission can be added at job level or workflow level
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  ddependabbot:
    runs-on: ubuntu-latest
    steps:
      - name: Fetchhh deffpendabot metadata
        run:  echo checkinggggg ${{ github.event.pull_request.user.login}}
