# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Data Prepper AWS secrets End-to-end test with Gradle
on:
  push:
    branches: [ main ]
  pull_request_target:
    types: [ opened, synchronize, reopened ]
  workflow_dispatch:
# permission can be added at job level or workflow level
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  build:
    strategy:
      matrix:
        java: [ 11, 17, 21, docker ]
        test: [ 'basicLogWithAwsSecretsEndToEndTest' ]
      fail-fast: false

    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Checkout Data Prepper
        uses: actions/checkout@v2
      - name: Run basic grok with AWS secrets end-to-end tests with Gradle
        run: AWS_PROFILE=default ./gradlew -PendToEndJavaVersion=${{ matrix.java }} :e2e-test:log:${{ matrix.test }}
